version: "3.7"

networks:
  async-net:
    external: true

volumes:
  postgres-data:

services:
  postgres:
    image: "postgres:14.2"
    container_name: async-net_postgres
    environment:
      POSTGRES_PASSWORD: "p0stGr3s"
    ports:
      - "5432:5432"
    networks:
      - async-net
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: on-failure
